# Terragon Autonomous SDLC Configuration
# Perpetual Value Discovery & Autonomous Enhancement Framework

repository:
  name: "causal-eval-bench"
  maturity_level: "maturing"
  assessment_date: "2025-08-01"
  last_value_discovery: "2025-08-01"

# =============================================================================
# ADAPTIVE SCORING WEIGHTS (Optimized for Maturing Repositories)
# =============================================================================

scoring:
  weights:
    wsjf: 0.6        # Higher weight on business value delivery
    ice: 0.1         # Lower confidence in estimates at this maturity
    technicalDebt: 0.2  # Moderate focus on technical debt
    security: 0.1    # Baseline security focus

  thresholds:
    minScore: 15         # Higher threshold for mature repo
    maxRisk: 0.7         # Moderate risk tolerance
    securityBoost: 2.0   # Double priority for security issues
    complianceBoost: 1.8 # Strong compliance focus

  priorities:
    # Maturing repository focus areas
    - advanced_testing
    - security_enhancements
    - operational_excellence
    - developer_experience
    - performance_optimization

# =============================================================================
# CONTINUOUS VALUE DISCOVERY CONFIGURATION
# =============================================================================

discovery:
  sources:
    enabled:
      - gitHistory
      - staticAnalysis
      - securityScanning
      - performanceMonitoring
      - dependencyAuditing
      - documentationGaps
      - testCoverageGaps
      - architecturalDebt

  tools:
    staticAnalysis:
      - ruff
      - mypy
      - bandit
      - sonarqube
    
    security:
      - safety
      - bandit
      - semgrep
      - trivy
      
    performance:
      - pytest-benchmark
      - memory_profiler
      - py-spy
      
    quality:
      - coverage
      - complexity-analysis
      - maintainability-index

  schedules:
    immediate: ["security_vulnerabilities", "build_failures", "test_failures"]
    hourly: ["dependency_updates", "security_scans"]
    daily: ["static_analysis", "performance_regression", "documentation_freshness"]
    weekly: ["architecture_review", "technical_debt_assessment"]
    monthly: ["strategic_value_alignment", "tool_modernization"]

# =============================================================================
# EXECUTION CONFIGURATION
# =============================================================================

execution:
  parallelism:
    maxConcurrentTasks: 1
    batchSize: 3
    
  quality_gates:
    required:
      - test_coverage_maintained: 80
      - security_scan_pass: true
      - linting_pass: true
      - type_checking_pass: true
      - build_success: true
    
    performance:
      maxRegressionPercent: 5
      benchmarkThreshold: 0.95
      
  rollback:
    triggers:
      - test_failure
      - build_failure  
      - security_violation
      - performance_regression
    autoRollback: true
    preserveAttempts: 3

# =============================================================================
# VALUE CATEGORIES FOR MATURING REPOSITORIES
# =============================================================================

value_categories:
  high_impact:
    - security_vulnerability_fix
    - performance_critical_path_optimization
    - test_coverage_gap_closure
    - documentation_critical_gaps
    - dependency_security_updates
    
  medium_impact:
    - code_quality_improvements
    - developer_experience_enhancements
    - monitoring_and_observability
    - ci_cd_optimization
    - architectural_improvements
    
  low_impact:
    - code_style_consistency
    - documentation_polish
    - dependency_minor_updates
    - configuration_standardization
    - housekeeping_tasks

# =============================================================================
# MATURITY PROGRESSION TRACKING
# =============================================================================

maturity:
  current: 65
  target: 85
  
  advancement_criteria:
    70:
      - github_actions_activated
      - comprehensive_security_scanning
      - performance_monitoring_active
      - documentation_completeness_90
      
    75:
      - advanced_deployment_strategies
      - chaos_engineering_basic
      - observability_full_stack
      - automated_dependency_management
      
    80:
      - self_healing_systems
      - predictive_maintenance
      - advanced_analytics_integration
      - compliance_automation
      
    85:
      - autonomous_optimization
      - ml_assisted_development
      - continuous_architecture_evolution
      - innovation_pipeline_active

# =============================================================================
# REPORTING AND METRICS
# =============================================================================

reporting:
  frequency:
    value_discovery: "daily"
    execution_summary: "weekly" 
    maturity_assessment: "monthly"
    strategic_review: "quarterly"
    
  metrics:
    track:
      - value_items_discovered
      - execution_success_rate
      - cycle_time_average
      - technical_debt_trend
      - security_posture_score
      - developer_productivity_index
      - system_reliability_metrics
      
  outputs:
    - backlog_markdown
    - value_metrics_json
    - executive_dashboard
    - technical_report

# =============================================================================
# INTEGRATION POINTS
# =============================================================================

integrations:
  version_control:
    platform: "github"
    auto_pr_creation: true
    branch_protection: true
    
  monitoring:
    prometheus: true
    grafana: true
    alertmanager: true
    
  security:
    snyk: false
    github_security_advisories: true
    dependabot: true
    
  deployment:
    docker: true
    kubernetes: false
    helm: false

# =============================================================================
# LEARNING AND ADAPTATION
# =============================================================================

learning:
  feedback_loops:
    enabled: true
    confidence_adjustment: true
    effort_recalibration: true
    value_prediction_tuning: true
    
  data_retention:
    execution_history_days: 365
    metrics_history_days: 730
    learning_model_versions: 10
    
  adaptation:
    scoring_model_updates: "monthly"
    threshold_adjustments: "quarterly"
    strategy_evolution: "biannual"