# Hadolint configuration for Dockerfile linting
# See: https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  - DL3008  # Pin versions in apt get install (acceptable for base images)
  - DL3009  # Delete the apt-get lists after installing (handled by base image)
  - DL3015  # Avoid additional packages by specifying --no-install-recommends
  # - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT
  # - DL4006  # Set the SHELL option -o pipefail before RUN with a pipe in it

# Override specific rules
override:
  error:
    - DL3003  # Use WORKDIR to switch to a directory
    - DL3020  # Use COPY instead of ADD for files and folders
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  warning:
    - DL3007  # Using latest is prone to errors
    - DL3033  # Specify version with yum install
  info:
    - DL3032  # yum clean all missing
  style: []

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
  - quay.io
  - registry-debug.com
  - mcr.microsoft.com

# Allow specific labels
allowedLabels:
  - maintainer
  - version
  - description
  - org.opencontainers.image.title
  - org.opencontainers.image.description
  - org.opencontainers.image.version
  - org.opencontainers.image.created
  - org.opencontainers.image.source
  - org.opencontainers.image.licenses
  - org.opencontainers.image.documentation
  - org.opencontainers.image.vendor
  - org.label-schema.build-date
  - org.label-schema.name
  - org.label-schema.description
  - org.label-schema.version
  - org.label-schema.schema-version

# Strict label validation
strictLabels: false

# Disable inline ignore comments
disableIgnoreComments: false

# Failure threshold
failure-threshold: error