name: ✨ Feature Request
description: Suggest a new feature or enhancement for Causal Eval Bench
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the roadmap and this feature is not already planned
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: Describe what you'd like to see implemented...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - New Evaluation Task
        - Domain-Specific Enhancement
        - Performance Improvement
        - API Enhancement
        - CLI Enhancement
        - Analysis Tool
        - Documentation
        - Infrastructure/DevOps
        - Research Tool
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Detailed Use Case
      description: Provide a detailed description of how you would use this feature
      placeholder: |
        Describe a specific scenario where you would use this feature:
        1. I want to...
        2. So that I can...
        3. This would help me...

  - type: textarea
    id: example
    attributes:
      label: Example Implementation
      description: If applicable, provide a code example or mockup of how this feature might work
      render: python
      placeholder: |
        # Example of how the feature might be used
        from causal_eval import NewFeature
        
        feature = NewFeature()
        result = feature.do_something()

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature should do X
        - [ ] Feature should handle Y case
        - [ ] Feature should have tests
        - [ ] Feature should be documented

  - type: dropdown
    id: research-impact
    attributes:
      label: Research Impact
      description: How would this feature impact causal reasoning research?
      options:
        - High - Enables new research directions
        - Medium - Improves existing research workflows
        - Low - Minor research benefit
        - None - Not research-related
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can provide domain expertise/guidance
        - label: I can help with testing and validation
        - label: I can help with documentation
        - label: I can provide code review

  - type: textarea
    id: resources
    attributes:
      label: Additional Resources
      description: Any relevant papers, examples, or resources related to this feature
      placeholder: |
        - Links to relevant research papers
        - Examples from other tools/frameworks
        - Documentation or specifications

  - type: dropdown
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you ideally like to see this feature implemented?
      options:
        - Next patch release
        - Next minor release
        - Next major release
        - When someone has time to work on it
        - No specific timeline

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or information about the feature request
      placeholder: Add any other context about the feature request here...